apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-basic-helm.name" . }}
  labels:
    {{- include "hello-basic-helm.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicaCount }}
  # Recreate = required because of the ReadWriteOnce PVC below.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "hello-basic-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-basic-helm.labels" . | nindent 8 }}
    spec:
      containers:
        - name: node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "hello-basic-helm.name" . }}-config
          env:
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "hello-basic-helm.name" . }}-secret
                  key: API_KEY
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

        - name: redis
          image: {{ .Values.redis.image }}
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --dir
            - /data
          ports:
            - containerPort: 6379
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          {{- end }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}

      {{- if .Values.persistence.enabled }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "hello-basic-helm.name" . }}-redis-data
      {{- end }}
