apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-basic-helm.name" . }}-secret
  labels:
    {{- include "hello-basic-helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
