apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-basic-helm.name" . }}
  labels:
    {{- include "hello-basic-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "hello-basic-helm.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
