apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-basic
  labels:
    app: hello-basic
    example: "01-basic"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-basic
  template:
    metadata:
      labels:
        app: hello-basic
    spec:
      containers:
        - name: node
          image: europe-central2-docker.pkg.dev/argocd-study-1775564129/playground/hello-basic:8678a21
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: hello-basic-config
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
