apiVersion: v1
kind: Service
metadata:
  name: hello-basic
  labels:
    app: hello-basic
    example: "01-basic"
spec:
  type: LoadBalancer
  selector:
    app: hello-basic
  ports:
    - port: 80
      targetPort: 80
