apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-helm
  labels:
    app: hello-helm
    example: "04-helm"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-helm
  template:
    metadata:
      labels:
        app: hello-helm
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
