apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-waves
  labels:
    app: hello-waves
    example: "05-sync-waves"
  annotations:
    # Wave 1 — only created after wave 0 (the ConfigMap) is healthy
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-waves
  template:
    metadata:
      labels:
        app: hello-waves
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: hello-waves-config
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
