apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-basic-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yuradmytriev/argocd-playground.git
    targetRevision: HEAD
    path: 01-basic-helm
    helm:
      # Override values here if you want to diverge from values.yaml
      # without editing the chart.
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: playground-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
